# Site settings
title: HTGS
email: timothy.blattner@nist.gov
description: > # this means to ignore newlines until "baseurl:"
 The Hybrid Task Graph Scheduler API for high performance computing across multi-CPU and multi-GPU systems.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: none
github_username:  tblattner

include:
  - _any_connector_8hpp__dep__incl.map
  - _any_connector_8hpp__dep__incl.md5
  - _any_connector_8hpp__dep__incl.png
  - _any_connector_8hpp.html
  - _any_connector_8hpp_source.html
  - _any_i_rule_8hpp__dep__incl.map
  - _any_i_rule_8hpp__dep__incl.md5
  - _any_i_rule_8hpp__dep__incl.png
  - _any_i_rule_8hpp.html
  - _any_i_rule_8hpp_source.html
  - _any_i_task_8hpp__dep__incl.map
  - _any_i_task_8hpp__dep__incl.md5
  - _any_i_task_8hpp__dep__incl.png
  - _any_i_task_8hpp.html
  - _any_i_task_8hpp_source.html
  - _any_memory_allocator_8hpp__dep__incl.map
  - _any_memory_allocator_8hpp__dep__incl.md5
  - _any_memory_allocator_8hpp__dep__incl.png
  - _any_memory_allocator_8hpp.html
  - _any_memory_allocator_8hpp_source.html
  - _any_rule_manager_8hpp__dep__incl.map
  - _any_rule_manager_8hpp__dep__incl.md5
  - _any_rule_manager_8hpp__dep__incl.png
  - _any_rule_manager_8hpp.html
  - _any_rule_manager_8hpp_source.html
  - _any_rule_manager_in_only_8hpp__dep__incl.map
  - _any_rule_manager_in_only_8hpp__dep__incl.md5
  - _any_rule_manager_in_only_8hpp__dep__incl.png
  - _any_rule_manager_in_only_8hpp.html
  - _any_rule_manager_in_only_8hpp_source.html
  - _any_task_graph_conf_8hpp__dep__incl.map
  - _any_task_graph_conf_8hpp__dep__incl.md5
  - _any_task_graph_conf_8hpp__dep__incl.png
  - _any_task_graph_conf_8hpp.html
  - _any_task_graph_conf_8hpp.js
  - _any_task_graph_conf_8hpp_source.html
  - _any_task_manager_8hpp__dep__incl.map
  - _any_task_manager_8hpp__dep__incl.md5
  - _any_task_manager_8hpp__dep__incl.png
  - _any_task_manager_8hpp.html
  - _any_task_manager_8hpp_source.html
  - _blocking_queue_8hpp__dep__incl.map
  - _blocking_queue_8hpp__dep__incl.md5
  - _blocking_queue_8hpp__dep__incl.png
  - _blocking_queue_8hpp.html
  - _blocking_queue_8hpp_source.html
  - _bookkeeper_8hpp__dep__incl.map
  - _bookkeeper_8hpp__dep__incl.md5
  - _bookkeeper_8hpp__dep__incl.png
  - _bookkeeper_8hpp.html
  - _bookkeeper_8hpp_source.html
  - _connector_8hpp__dep__incl.map
  - _connector_8hpp__dep__incl.md5
  - _connector_8hpp__dep__incl.png
  - _connector_8hpp.html
  - _connector_8hpp_source.html
  - _cuda_memory_manager_8hpp__dep__incl.map
  - _cuda_memory_manager_8hpp__dep__incl.md5
  - _cuda_memory_manager_8hpp__dep__incl.png
  - _cuda_memory_manager_8hpp.html
  - _cuda_memory_manager_8hpp_source.html
  - _data_packet_8hpp__dep__incl.map
  - _data_packet_8hpp__dep__incl.md5
  - _data_packet_8hpp__dep__incl.png
  - _data_packet_8hpp.html
  - _data_packet_8hpp_source.html
  - _edge_descriptor_8hpp__dep__incl.map
  - _edge_descriptor_8hpp__dep__incl.md5
  - _edge_descriptor_8hpp__dep__incl.png
  - _edge_descriptor_8hpp.html
  - _edge_descriptor_8hpp_source.html
  - _execution_pipeline_8hpp.html
  - _execution_pipeline_8hpp_source.html
  - _execution_pipeline_broadcast_rule_8hpp__dep__incl.map
  - _execution_pipeline_broadcast_rule_8hpp__dep__incl.md5
  - _execution_pipeline_broadcast_rule_8hpp__dep__incl.png
  - _execution_pipeline_broadcast_rule_8hpp.html
  - _execution_pipeline_broadcast_rule_8hpp_source.html
  - _i_cuda_task_8hpp.html
  - _i_cuda_task_8hpp_source.html
  - _i_data_8hpp__dep__incl.map
  - _i_data_8hpp__dep__incl.md5
  - _i_data_8hpp__dep__incl.png
  - _i_data_8hpp.html
  - _i_data_8hpp_source.html
  - _i_memory_allocator_8hpp__dep__incl.map
  - _i_memory_allocator_8hpp__dep__incl.md5
  - _i_memory_allocator_8hpp__dep__incl.png
  - _i_memory_allocator_8hpp.html
  - _i_memory_allocator_8hpp_source.html
  - _i_memory_release_rule_8hpp__dep__incl.map
  - _i_memory_release_rule_8hpp__dep__incl.md5
  - _i_memory_release_rule_8hpp__dep__incl.png
  - _i_memory_release_rule_8hpp.html
  - _i_memory_release_rule_8hpp_source.html
  - _i_rule_8hpp__dep__incl.map
  - _i_rule_8hpp__dep__incl.md5
  - _i_rule_8hpp__dep__incl.png
  - _i_rule_8hpp.html
  - _i_rule_8hpp_source.html
  - _i_task_8hpp__dep__incl.map
  - _i_task_8hpp__dep__incl.md5
  - _i_task_8hpp__dep__incl.png
  - _i_task_8hpp.html
  - _i_task_8hpp_source.html
  - _memory_data_8hpp__dep__incl.map
  - _memory_data_8hpp__dep__incl.md5
  - _memory_data_8hpp__dep__incl.png
  - _memory_data_8hpp.html
  - _memory_data_8hpp_source.html
  - _memory_edge_8hpp__dep__incl.map
  - _memory_edge_8hpp__dep__incl.md5
  - _memory_edge_8hpp__dep__incl.png
  - _memory_edge_8hpp.html
  - _memory_edge_8hpp_source.html
  - _memory_manager_8hpp__dep__incl.map
  - _memory_manager_8hpp__dep__incl.md5
  - _memory_manager_8hpp__dep__incl.png
  - _memory_manager_8hpp.html
  - _memory_manager_8hpp_source.html
  - _memory_pool_8hpp__dep__incl.map
  - _memory_pool_8hpp__dep__incl.md5
  - _memory_pool_8hpp__dep__incl.png
  - _memory_pool_8hpp.html
  - _memory_pool_8hpp_source.html
  - _m_m_type_8hpp__dep__incl.map
  - _m_m_type_8hpp__dep__incl.md5
  - _m_m_type_8hpp__dep__incl.png
  - _m_m_type_8hpp.html
  - _m_m_type_8hpp.js
  - _m_m_type_8hpp_source.html
  - _priority_blocking_queue_8hpp__dep__incl.map
  - _priority_blocking_queue_8hpp__dep__incl.md5
  - _priority_blocking_queue_8hpp__dep__incl.png
  - _priority_blocking_queue_8hpp.html
  - _priority_blocking_queue_8hpp_source.html
  - _producer_consumer_edge_8hpp__dep__incl.map
  - _producer_consumer_edge_8hpp__dep__incl.md5
  - _producer_consumer_edge_8hpp__dep__incl.png
  - _producer_consumer_edge_8hpp.html
  - _producer_consumer_edge_8hpp_source.html
  - _rule_edge_8hpp__dep__incl.map
  - _rule_edge_8hpp__dep__incl.md5
  - _rule_edge_8hpp__dep__incl.png
  - _rule_edge_8hpp.html
  - _rule_edge_8hpp_source.html
  - _rule_manager_8hpp__dep__incl.map
  - _rule_manager_8hpp__dep__incl.md5
  - _rule_manager_8hpp__dep__incl.png
  - _rule_manager_8hpp.html
  - _rule_manager_8hpp_source.html
  - _task_graph_communicator_8hpp__dep__incl.map
  - _task_graph_communicator_8hpp__dep__incl.md5
  - _task_graph_communicator_8hpp__dep__incl.png
  - _task_graph_communicator_8hpp.html
  - _task_graph_communicator_8hpp.js
  - _task_graph_communicator_8hpp_source.html
  - _task_graph_conf_8hpp__dep__incl.map
  - _task_graph_conf_8hpp__dep__incl.md5
  - _task_graph_conf_8hpp__dep__incl.png
  - _task_graph_conf_8hpp.html
  - _task_graph_conf_8hpp_source.html
  - _task_graph_dot_gen_flags_8hpp__dep__incl.map
  - _task_graph_dot_gen_flags_8hpp__dep__incl.md5
  - _task_graph_dot_gen_flags_8hpp__dep__incl.png
  - _task_graph_dot_gen_flags_8hpp.html
  - _task_graph_dot_gen_flags_8hpp.js
  - _task_graph_dot_gen_flags_8hpp_source.html
  - _task_graph_profiler_8hpp__dep__incl.map
  - _task_graph_profiler_8hpp__dep__incl.md5
  - _task_graph_profiler_8hpp__dep__incl.png
  - _task_graph_profiler_8hpp.html
  - _task_graph_profiler_8hpp_source.html
  - _task_graph_runtime_8hpp__dep__incl.map
  - _task_graph_runtime_8hpp__dep__incl.md5
  - _task_graph_runtime_8hpp__dep__incl.png
  - _task_graph_runtime_8hpp.html
  - _task_graph_runtime_8hpp_source.html
  - _task_graph_signal_handler_8hpp.html
  - _task_graph_signal_handler_8hpp_source.html
  - _task_manager_8hpp__dep__incl.map
  - _task_manager_8hpp__dep__incl.md5
  - _task_manager_8hpp__dep__incl.png
  - _task_manager_8hpp.html
  - _task_manager_8hpp_source.html
  - _task_manager_profile_8hpp__dep__incl.map
  - _task_manager_profile_8hpp__dep__incl.md5
  - _task_manager_profile_8hpp__dep__incl.png
  - _task_manager_profile_8hpp.html
  - _task_manager_profile_8hpp_source.html
  - _types_8hpp__dep__incl.map
  - _types_8hpp__dep__incl.md5
  - _types_8hpp__dep__incl.png
  - _types_8hpp.html
  - _types_8hpp.js
  - _types_8hpp_source.html
  - _void_data_8hpp__dep__incl.map
  - _void_data_8hpp__dep__incl.md5
  - _void_data_8hpp__dep__incl.png
  - _void_data_8hpp.html
  - _void_data_8hpp_source.html

# Build settings
markdown: kramdown
